
default:
  data_base_dir: "data/synthetic"
  applications_filename: "applications_oktober_2024_synthetic.csv"

cambo:
  data_base_dir: "data/cambo"
  applications_filename: "applications_oktober_2024.csv"
