
default:
  suffix: "_DEMO"
  applications_filename: "aanmeldingen_oktober_2024_DEMO.csv"

cambo:
  suffix: ""
  applications_filename: "aanmeldingen_oktober_2024.csv"

all:
  inherits: "default"
  prepare: false
  year: 2024

# korte verwijzing naar instelling zonder spaties
mboa:
  # "default" is de demo modus, "cambo" gebruikt echte data
  inherits: "cambo"
  # of de data_preparation opnieuw moet draaien. Als bestanden ontbreken, dan wordt dit automatisch gedaan
  prepare: false
  # echte brin, moet bestaan
  brin: "30RR"
  # naam instelling in de plots en tekst
  school_name: "MBO Amersfoort"
  # 2023 of 2024
  year: 2024

graafschap:
  # "default" is de demo modus, "cambo" gebruikt echte data
  inherits: "cambo"
  # of de data_preparation opnieuw moet draaien. Als bestanden ontbreken, dan wordt dit automatisch gedaan
  prepare: false
  # echte brin, moet bestaan
  brin: "24ZZ"
  # naam instelling in de plots en tekst
  school_name: "Graafschap College"
  # 2023 of 2024
  year: 2024

